name: Make
on:
  push:
    branches:
      - main
jobs:
  build-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          path: npm
          node-version: 18
      - uses: actions/checkout@v3
      - run: | 
          echo '
          {
            "$schema": "https://json.schemastore.org/semantic-release.json",
            "branches": [
              "main"
            ],
            "plugins": [
              [
                "@semantic-release/github",
                {
                  "assets": [
                    {
                      "path": "out/De Legitimaat.html",
                      "label": "De Legitimaat"
                    }
                  ]
                }
              ]
            ]
          } ' >> .release.rc

      - run: |
          mkdir ./output
          npx respec --localhost --src index.html --out "./output/De Legitimaat.html"
      - run: |
          npx semantic-release
