name: Make
on:
  push:
    branches:
      - main
jobs:
  build-html:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir ~/static
      - uses: actions/setup-node@v3
        with:
          path: npm
          node-version: 18
      - uses: actions/checkout@v3
      - run: |
          npx respec --localhost --src index.html --out "~/static/De Legitimaat.html"
      - run: |
          npx scemantic-release -p [
            ['@semantic-release/github', { "assets": ["~static/**"] } ]
          ]
