name: Make
on:
  push:
    branches:
      - main
jobs:
  build-html:
    runs-on: ubuntu-latest
    steps:
      - uses: onursagir/regels.overheid.nl/.github/actions/publish@main
        with:
          token: ${{ secrets.PUB_SECRET }}