name: Build and release
on:
  push:
    branches:
      - main
jobs:
  build-html:
    runs-on: ubuntu-latest
    steps:
      - uses: onursagir/regels.overheid.nl/.github/actions/build-and-release-respec-document@main
        with:
          name: "De MehmetMaat"
          token: ${{ secrets.GITHUB_TOKEN }}
          ##################