name: Notify regels.overheid.nl of new release
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  notify-api:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: echo "$TAG_NAME"
